### ISSUE TITLE
Week 15

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/SP17-barbot#10]
Final Decision on project status must be submitted to Dr. H by Monday, May 1.

**TODO**

- [x] Tune line follower sensor

- [x] Get robot to follow taped path

- [x] Finish Research Paper

- [x] Add performance metrics to robot code and gather data

- [x] Install battery for Braccio Arm
