### ISSUE TITLE
Week 9

### ISSUE THREAD

**Issue by joblolin95** [bwwagner/SP17-barbot#6]
**Robot Materials Checklist**
- [x] Color sensors

- [ ] IR Reflectance Sensors (for line following)

- [ ] Wood platform to put on carriage

- [x] Assembled arm

- [ ] Cardboard magazine(s) for mints

**TODO**

- [ ] Get project feedback from Dr H

- [ ] Put sturdier platform on carriage

- [ ] Mount arm on carriage

- [ ] Mount sensors on robot

**Comment by bwwagner** [comment]
Asked Dr H about a potential 5V battery at the RoboRumble.  He said he would check it out, but if he can't get anything he said we can just use an extension cord and/or shorten our delivery area.
