### ISSUE TITLE
Week #11

### ISSUE THREAD

**Issue by joblolin95** [bwwagner/SP17-barbot#7]
**TODO**

- [x] Mount color sensor on robot

- [x] Get color coded cards/coasters

- [x] Tune color sensor using cards/coasters

- [x] Get a table and mark the robot's path using duct tape

- [ ] Mount line follower sensor

- [ ] Tune line follower sensor

- [ ] Get robot to follow taped path

- [x] Mount arm on carriage

- [x] Create magazines for mint patties

- [x] Get arm to grab mint patties from magazine

- [x] Fix #8 

**Robot Materials Checklist**
- [x] Color sensors

- [x] IR Reflectance Sensors (for line following)

- [x] Wood platform to put on carriage

- [x] Assembled arm

- [x] Cardboard magazine(s) for mints

- [ ] Color coded coasters/cards

- [ ] Mobile Power Supply for Bracchio Arm

**Comment by joblolin95** [comment]
We're gettin' there guys!

**Comment by bwwagner** [comment]
Added a tick for #8.

Edit:
Issue solved. Great job guys!
