### ISSUE TITLE
Week 13

### ISSUE THREAD

**Issue by joblolin95** [bwwagner/SP17-barbot#9]
**TODO**

- [x] Mount line follower sensor

- [ ] Tune line follower sensor

- [ ] Get robot to follow taped path

- [x] Make a magazine to put mints in (!!)

- [x] Finish presentation for student conference
